common: &common
  adapter: postgresql
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: travel_dev

test:
  <<: *common
  database: travel_test

production:
  <<: *common
  database: travel

